document.write("Como lo llevas?")
document.write("<br>")
document.write("El exámen?")
document.write("<br>")
document.write("Sí")
document.write("<br>")
document.write("De momento bién")
//-----
document.write("Y tú?")
document.write("<br>")
document.write("Yo bién")
